# Generated by Django 5.1.5 on 2025-01-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=25)),
                ('car_name', models.CharField(max_length=200)),
                ('car_number', models.CharField(max_length=20)),
                ('cash', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=25)),
                ('cash', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('origin', models.CharField(max_length=600)),
                ('destination_lat', models.FloatField()),
                ('destination_lon', models.FloatField()),
                ('destination', models.CharField(max_length=600)),
                ('distance', models.FloatField()),
                ('amount', models.FloatField()),
                ('seats', models.IntegerField(choices=[(2, 'Two-seater'), (4, 'Four-seater'), (6, 'Six-seater'), (8, 'Eight-seater')], default=4)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('B', 'Booked'), ('V', 'Verified')], default='P', max_length=30)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rider')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
    ]
