# Generated by Django 5.1.5 on 2025-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='map_image',
            field=models.ImageField(default='map.png', upload_to='maps/'),
        ),
    ]
