# Generated by Django 5.1.5 on 2025-02-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trip_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rider',
            name='cash',
            field=models.FloatField(default=0),
        ),
    ]
